# BBC1

- alias: Alexa Play BBC1
  initial_state: true
  trigger:
    platform: state
    entity_id: input_boolean.alexa_bbc1
    from: 'off'
    to: 'on'
  action:
  - service: media_player.play_media
    data:
      entity_id: media_player.living_room
      media_content_id: BBC Radio 1
      media_content_type: TUNEIN
  - service: media_player.play_media
    data:
      entity_id: media_player.bathroom
      media_content_id: BBC Radio 1
      media_content_type: TUNEIN
  id: bcd085b7488d416ca26d83f8c6be9c03
 
- alias: Alexa stop BBC1
  initial_state: true
  trigger:
    platform: state
    entity_id: input_boolean.alexa_bbc1
    from: 'on'
    to: 'off'
  action:
  - service: media_player.turn_off
    data:
      entity_id: media_player.living_room
  - service: media_player.turn_off
    data:
      entity_id: media_player.bathroom
  id: 565c037472314641bceb482349dc8ed0

# Groove Salad

- alias: Alexa play Groove Salad
  initial_state: true
  trigger:
    platform: state
    entity_id: input_boolean.alexa_groove_salad
    from: 'off'
    to: 'on'
  action:
  - service: media_player.play_media
    data:
      entity_id: media_player.living_room
      media_content_id: Groove Salad
      media_content_type: TUNEIN
  - service: media_player.play_media
    data:
      entity_id: media_player.bathroom
      media_content_id: Groove Salad
      media_content_type: TUNEIN
  id: 3ed48cd3f3e7449dbdc43e86a9424dcb

- alias: Alexa stop Groove Salad
  initial_state: true
  trigger:
    platform: state
    entity_id: input_boolean.alexa_groove_salad
    from: 'on'
    to: 'off'
  action:
  - service: media_player.turn_off
    data:
      entity_id: media_player.living_room
  - service: media_player.turn_off
    data:
      entity_id: media_player.bathroom
  id: edf41615bdcb4f4aaa674e509637a41a

# Radio 6

- alias: Alexa play BBC Radio6
  initial_state: true
  trigger:
    platform: state
    entity_id: input_boolean.alexa_bbcradio6
    from: 'off'
    to: 'on'
  action:
  - service: media_player.play_media
    data:
      entity_id: media_player.living_room
      media_content_id: BBC Radio Six
      media_content_type: TUNEIN
  - service: media_player.play_media
    data:
      entity_id: media_player.bathroom
      media_content_id: BBC Radio Six
      media_content_type: TUNEIN
  id: 40d38f6fac7947849ce3b3b6528b1084

- alias: Alexa stop Radio6
  initial_state: true
  trigger:
    platform: state
    entity_id: input_boolean.alexa_bbcradio6
    from: 'on'
    to: 'off'
  action:
  - service: media_player.turn_off
    data:
      entity_id: media_player.living_room
  - service: media_player.turn_off
    data:
      entity_id: media_player.bathroom
  id: 02744ac67e3644a290f8fd15781ae51e

# Meditation Radio

- alias: Alexa Meditation Radio again
  initial_state: true
  trigger:
    platform: state
    entity_id: input_boolean.alexa_meditation_radio
    from: 'off'
    to: 'on'
  action:
  - service: media_player.play_media
    data:
      entity_id: media_player.living_room
      media_content_id: Nirvana Meditation Radio
      media_content_type: TUNEIN
  - service: media_player.play_media
    data:
      entity_id: media_player.bathroom
      media_content_id: Nirvana Meditation Radio
      media_content_type: TUNEIN
  id: f8e3ab0dcf65487ba1ca49e36b997a18

- alias: Alexa play Meditation Radio
  initial_state: true
  trigger:
    platform: state
    entity_id: input_boolean.alexa_meditation_radio
    from: 'on'
    to: 'off'
  action:
  - service: media_player.turn_off
    data:
      entity_id: media_player.living_room
  - service: media_player.turn_off
  id: 1581d71e9a9a498a9746340cd17623b6


  # TV switch on
- alias: TV switch on
  initial_state: true
  trigger:
    platform: state
    entity_id: input_boolean.tv
    from: 'off'
    to: 'on'
  condition:
    - condition: state
      entity_id: switch.onkyo_power
      state: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.lg_tv
    - service: homeassistant.turn_on
      entity_id: switch.android_tv
    - service: homeassistant.turn_on
      entity_id: switch.onkyo_power 
    - service: homeassistant.turn_on
      entity_id: switch.tv_speakers 
  
# TV switch on
- alias: TV switch off
  initial_state: true
  trigger:
    platform: state
    entity_id: input_boolean.tv
    from: 'on'
    to: 'off'
  condition:
    - condition: state
      entity_id: switch.onkyo_power
      state: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: switch.lg_tv
    - service: homeassistant.turn_off
      entity_id: switch.android_tv
    - service: homeassistant.turn_off
      entity_id: switch.onkyo_power 
    - service: homeassistant.turn_off
      entity_id: switch.tv_speakers 
