# Livingroom blinds

- alias: Livingroom Blinds pull down
  initial_state: true
  trigger:
    - platform: numeric_state
      entity_id: sensor.blinds_livingroom_lux
      below: 60
  condition:
    - condition: state
      entity_id: input_boolean.blinds_livingroom
      state: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id: script.livingroom_blinds_down
  
- alias: Livingroom Blinds pull up
  initial_state: true
  trigger:
    - platform: numeric_state
      entity_id: sensor.blinds_livingroom_lux
      above: 80
  condition:
    - condition: state
      entity_id: input_boolean.blinds_livingroom
      state: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id: script.livingroom_blinds_up


# Kitchen blinds

- alias: Kitchen Blinds pull down
  initial_state: true
  trigger:
    - platform: numeric_state
      entity_id: sensor.blinds_kitchen_lux
      below: 90
  condition:
    - condition: state
      entity_id: input_boolean.blinds_kitchen
      state: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id: script.kitchen_blinds_down
    - delay: 00:00:08
    - service: homeassistant.turn_on
      entity_id: script.kitchen_blinds_stop
  
- alias: Kitchen Blinds pull up
  initial_state: true
  trigger:
    - platform: numeric_state
      entity_id: sensor.blinds_kitchen_lux
      above: 120
  condition:
    - condition: state
      entity_id: input_boolean.blinds_kitchen
      state: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id: script.kitchen_blinds_up
  

# Black bathroom motion detection

- alias: Black Bathroom PIR on
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.bathroom_pir
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.bathroom_pir
      state: 'on'
  action:
    - service: script.turn_off
      entity_id: script.blackbath_lighton_10min
    - service: homeassistant.turn_on
      entity_id: script.blackbath_lighton_10min
    #- service: media_player.play_media
    #  data:
    #    entity_id: media_player.bathroom
    #    media_content_id: Groove Salad
    #    media_content_type: TUNEIN
    #- delay: 00:10:00
    #- service: media_player.turn_off
    #  data:
    #    entity_id: media_player.bathroom

- alias: Black Bathroom PIR off
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_boolean.bathroom_pir
      from: 'on'
      to: 'off'
  action:
    - service: automation.turn_off
      entity_id: automation.black_bathroom_pir_on
    - service: script.turn_off
      entity_id: script.blackbath_lighton_10min


# Livingroom Motion Detection 

- alias: Livingroom PIR on
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.livingroom_pir
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id:  input_boolean.livingroom_pir
      state: 'on'
  action:
    - service: script.turn_off
      entity_id: script.livingroom_lighton_10min
    - service: homeassistant.turn_on
      entity_id: script.livingroom_lighton_10min
    
- alias: Livingroom PIR stop
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_boolean.livingroom_pir
      from: 'on'
      to: 'off'
  action:
    - service: automation.turn_off
      entity_id: automation.livingroom_pir_on
    - service: script.turn_off
      entity_id: script.livingroom_lighton_10min


# Ventilation on ensuite PIR

- alias: Ventilation ensuite PIR on
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.bedroom_pir
      from: 'off'
      to: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.ventilation


# Ventilation triggered by extractor fan in Kitchen

- alias: Ventilation extractor fan dummy switch
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.extractor_fan
      from: 'off'
      to: 'on'
  action:
    - delay: 00:00:02
    - service: homeassistant.turn_on
      entity_id: input_boolean.extractor_fan_dummy
    - delay: 00:00:03
    - service: homeassistant.turn_off
      entity_id: input_boolean.extractor_fan_dummy

- alias: Ventilation extractor fan on
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.extractor_fan
      from: 'off'
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.extractor_fan_dummy
      state: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id: switch.ventilation


# Octoprint finish announcement

- alias: Octoprint finished printing
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.octoprint_printing
      from: 'on'
      to: 'off'
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.3d_printer_finished
    - service: media_player.alexa_tts
      data_template:
        entity_id: media_player.living_room
        message: The 3D printer has finished printing


# Mailbox motion sensor

- alias: Mailbox motion sensor
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor
      from: 'off'
      to: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.you_got_mail
    - service: media_player.alexa_tts
      data_template:
        entity_id: media_player.living_room
        message: You've got mail. No not that sort of mail. Real mail!


# Washing machine has finished

#- alias: Washing machine has finished
#  initial_state: true
#  trigger:
#    - platform: numeric_state
#      entity_id: sensor.washing_machine_watts
#      below: 1.3
      #for:
      #  minutes: 10
#  action:
#    - service: homeassistant.turn_on
#      entity_id: 
#      - input_boolean.washing_machine_finished
#      - script.wm_loop


# Washing machine input select from standby to running

- alias: Set washing machine running
  initial_state: true
  trigger:
    - platform: numeric_state
      entity_id: sensor.washing_machine_watts
      above: 2
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_select.washing_machine_status
        state: Standby
      - condition: state
        entity_id: input_select.washing_machine_status
        state: Finished  
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.washing_machine_status
        option: Running

# Washing machine input select from running to finished
 
- alias: Set washing machine finished
  initial_state: true
  trigger:
    - platform: numeric_state
      entity_id: sensor.washing_machine_watts
      below: 2
  condition:
      - condition: state
        entity_id: input_select.washing_machine_status
        state: Running
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.washing_machine_status
        option: Finished
    - service: homeassistant.turn_on
      entity_id: 
        - input_boolean.washing_machine_finished
        - script.wm_loop


# Washing machine reset

- alias: Washing Machine reset
  initial_state: true
  trigger:
    - platform: state
      entity_id: input_boolean.washing_machine_finished
      from: 'on'
      to: 'off'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.washing_machine_status
        option: Standby