resources:
  - url: https://cdn.jsdelivr.net/gh/bramkragten/custom-ui@master/weather-card/weather-card.min.js
    type: module

    
title: Our Amazing Home
views:
  - !include /config/lovelace/00_cameras_view.yaml
  - !include /config/lovelace/10_floorplan_view.yaml
  - !include /config/lovelace/50_weather_view.yaml
  - !include /config/lovelace/40_media_view.yaml
  - !include /config/lovelace/20_upstairs_view.yaml
  - !include /config/lovelace/21_utilityroom_view.yaml
  - !include /config/lovelace/30_downstairs_view.yaml
  - !include /config/lovelace/90_raspberry_pi_view.yaml




          
          